[versions]
dokka = "1.9.10"
kotest = "5.7.2"
kotlin = "1.9.20"
testkit = "0.9.0"

[libraries]
java-qa = "org.danilopianini:gradle-java-qa:1.22.1"
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.7.0.202309050840-r"
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
turtle = "com.lordcodes.turtle:turtle:0.8.0"

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:2.0.1"
gradlePluginPublish = "com.gradle.plugin-publish:1.2.1"
jacoco-testkit = "pl.droidsonroids.jacoco.testkit:1.0.12"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.53.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.6"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.17-dev0o-2bc03d2"
taskTree = "com.dorongold.task-tree:2.1.1"
